### ISSUE TITLE
Support image resources with no extension information

### ISSUE THREAD

**Issue by F1LT3R** [scijs/get-pixels#13]
What about image resources that have no extension information, such as these cute dogs from Google?

``` javascript
// Image resource without extension
https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbCMLPY5OhKVYQRaLoz6UMUoZe4e57SA01OCY_0eZEfiDUIBLxp4HUA6_S
```

![Cute Dogs From Google](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSbCMLPY5OhKVYQRaLoz6UMUoZe4e57SA01OCY_0eZEfiDUIBLxp4HUA6_S)

**Comment by quaidesapps** [comment]
Hi, same issue with this module and pixel-getter. Works nicely when simple node and error when Dockerized. I can read the url in my browser. I was thing a user right thing: anyone has a clue?

**Comment by ericosg** [comment]
this is not resolved and should be re-opened. no extension would be a nice feature. not sure if a workaround is specifying the mime type, but then again how would you support different file types?
